Traceback (most recent call last):
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\iuriol\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from matplotlib import pyplot as plt 
import numpy as np
import warnings

h = 6.62607015e-34 
c = 2.99792458e+8
k = 1.380649e-23 
pi = np.pi

warnings.filterwarnings('ignore')


def planck(wav, T):
    a = 2.0*pi*h*c**2
    b = h*c/(wav*k*T)
    intensity = a/((wav**5)*(np.exp(b)-1.0))
	lambdamax = 2898/T
	maxintensity = a/((lambdamax**5)*(np.exp(b)-1.0))
    return intensity
	return maxintensity

wavelengths = np.arange(1e-9, 3e-6, 1e-9)

temperatures = [5788, 372, 252]

for T in temperatures:
    intensity = planck(wavelengths, T)
    plt.plot(wavelengths*1e9, intensity*1e-12, label=f"T={T}K")
	plt.plot(wavelengths*1e9, intensity/maxintensity, label=f"T={T}K")

plt.xlabel("Wavelength (nm)")
plt.ylabel("Intensity (W/m^3)")
plt.title("Planck's Law")
plt.legend()
plt.show()
------------------


[1;36m  File [1;32m<string>:17[1;36m[0m
[1;33m    lambdamax = 2898/T[0m
[1;37m                      ^[0m
[1;31mTabError[0m[1;31m:[0m inconsistent use of tabs and spaces in indentation


